spring:
  application:
    name: "uploader"
  datasource:
    url: jdbc:postgresql://scuo-db01/wcsdb
    username: wcsuser
    password: ohwah7eubee7Eerahziphei8
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: true
        globally_quoted_identifiers: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        jdbc:
          batch_size: 5000
          order_inserts: true


    show_sql: true
    format_sql: true
    use_sql_comments: true




logging:
  file: /home/rataullin/application-debug.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR




